export const postTexts = [
    "Hoy es un gran día para aprender algo nuevo. ¡La programación es increíble! 🚀 #CodingLife",
    "Recientemente empecé a leer un libro fascinante sobre inteligencia artificial. ¡Recomendadísimo! 🤖📚",
    "No puedo creer lo rápido que pasa el tiempo. Parece que fue ayer cuando empecé este proyecto... ⏳",
    "Consejo del día: nunca subestimes el poder de una buena taza de café para comenzar la jornada ☕️😊",
    "Acabo de probar una nueva receta de pasta, ¡y quedó deliciosa! 🍝 ¿Alguien más amante de la cocina por aquí?",
    "Esos días en los que todo sale bien... ¡son los mejores! 😎🌞 #FeelingGood",
    "Desafío del día: escribir al menos 10 líneas de código sin errores. ¡A ver quién se anima! 💻💪",
    "Reflexionando sobre lo importante que es tomarse un tiempo para uno mismo. A veces, desconectar es necesario. 🌱✨",
    "La música lo cambia todo. Una buena playlist puede transformar hasta el día más gris 🎧🎶 #MoodBooster",
    "Estoy súper emocionado con mi nuevo proyecto, pero aún no puedo dar detalles. ¡Pronto les contaré! 😁🔜",
    "El amanecer de hoy fue espectacular. Nada como empezar el día con una vista tan hermosa 🌅❤️",
    "Mi película favorita siempre será esa que me hace reír y llorar al mismo tiempo. ¿Y la tuya? 🎥😂😢",
    "Compartiendo un pequeño logro: ¡por fin logré hacer funcionar ese código que me tenía bloqueado! 🎉🖥️",
    "A veces solo necesitas un buen libro, una taza de té y un lugar tranquilo para ser feliz 📖🍵 #Relax",
    "Recordatorio: Nunca es tarde para empezar algo nuevo. ¡Vamos a por ello! 💪🚀 #Motivation",
    "Pasé el día explorando una ciudad nueva, ¡y me encantó cada rincón! 🗺️✨ #TravelDiaries",
    "Me siento agradecido por todas las personas increíbles que me rodean. Ustedes hacen mi vida mejor 🙏❤️",
    "El trabajo en equipo siempre rinde más frutos que ir solo. ¡Orgulloso de mi equipo! 🤝💼",
    "Soñar en grande es el primer paso para alcanzar lo imposible. No dejes que nadie te diga lo contrario ✨💭",
    "Disfrutando de una noche tranquila con una buena serie y algo de chocolate 🍫📺. ¡La felicidad está en las pequeñas cosas!"
]

export const postComments = [
    "¡Me encanta! 😍",
    "Totalmente de acuerdo con esto. 👏",
    "No puedo creer que hayas dicho eso 😂",
    "¿Dónde compraste eso? ¡Necesito uno! 🛍️",
    "Esto es oro puro. ¡Gracias por compartir! 💯",
    "No estoy seguro de lo que piensas, pero a mí no me convence. 🤔",
    "Siempre me haces reír. 😂👌",
    "¡Gran foto! La luz es perfecta. 🌅",
    "¡Qué suerte tienes! Me encantaría estar ahí. 🌍✨",
    "Esto me recuerda a una experiencia que tuve. 😅",
    "Interesante punto de vista. Gracias por compartirlo. 🤔",
    "¡Eres una inspiración! Sigue brillando. ✨",
    "¿Alguien más se siente así? 🙋‍♂️",
    "¡Amo este lugar! He estado allí varias veces. ❤️",
    "Esto es tan cierto. Necesitamos más positividad. 🌈",
    "¡Qué divertido! Me encanta tu sentido del humor. 😂",
    "Siempre aportas algo valioso. Gracias. 🙏",
    "¿Quién más está obsesionado con esto? 🙌",
    "Esto es exactamente lo que necesitaba leer hoy. 📝💡",
    "¡Quiero probar eso! Se ve delicioso. 🍽️",
    "Esto me ha hecho reflexionar. Gracias por abrir los ojos. 👀"
]

export const postImages = [
    "https://images.pexels.com/photos/1089438/pexels-photo-1089438.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/13016654/pexels-photo-13016654.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/28879550/pexels-photo-28879550/free-photo-of-vista-panoramica-de-la-arquitectura-barroca-de-praga.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/28821822/pexels-photo-28821822.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/28834408/pexels-photo-28834408/free-photo-of-playa-resplandeciente-con-madera-a-la-deriva-al-atardecer.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/28217302/pexels-photo-28217302/free-photo-of-animal-pelo-piel-zoo.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/28523492/pexels-photo-28523492/free-photo-of-la-mansion-del-fundador-en-arequipa-peru.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/28905887/pexels-photo-28905887/free-photo-of-venecia.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/28753970/pexels-photo-28753970/free-photo-of-espectacular-puesta-de-sol-sobre-el-lago-fort-william-reino-unido.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/19228242/pexels-photo-19228242/free-photo-of-mujer-parque-transparente-en-pie.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/28425084/pexels-photo-28425084/free-photo-of-silueta-de-una-persona-con-bicicleta-bajo-el-cielo-estrellado.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/28412629/pexels-photo-28412629/free-photo-of-vista-aerea-de-un-laberinto-geometrico-de-maiz-en-verano.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/28494944/pexels-photo-28494944.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/12266858/pexels-photo-12266858.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/14000214/pexels-photo-14000214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/27793420/pexels-photo-27793420/free-photo-of-moda-gente-calle-pasos.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/28868268/pexels-photo-28868268.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/20350895/pexels-photo-20350895/free-photo-of-mujer-pared-muro-en-pie.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/16465970/pexels-photo-16465970/free-photo-of-una-mujer-posando-en-un-vasto-campo-de-flores-amarillas.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/20543294/pexels-photo-20543294/free-photo-of-gafas-de-sol-mujer-modelo-maqueta.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/27439088/pexels-photo-27439088/free-photo-of-hotel-edificio-construccion-tipografia.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/1546171/pexels-photo-1546171.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/2076261/pexels-photo-2076261.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/2257899/pexels-photo-2257899.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/2272965/pexels-photo-2272965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/2261474/pexels-photo-2261474.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/4140306/pexels-photo-4140306.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/2023220/pexels-photo-2023220.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/3184459/pexels-photo-3184459.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/3261750/pexels-photo-3261750.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/4311753/pexels-photo-4311753.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/3064235/pexels-photo-3064235.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/2736787/pexels-photo-2736787.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/1784236/pexels-photo-1784236.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    "https://images.pexels.com/photos/4040916/pexels-photo-4040916.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
]


