export const comments = [
    "¡Este es mi primer comentario en Twitter! 😃",
    "Totalmente de acuerdo con lo que mencionaste. 👏",
    "No puedo creer que esto esté sucediendo... 😱",
    "¡Qué gran noticia! 🎉 Felicidades a todos los involucrados.",
    "Este tema siempre causa mucho debate, pero creo que es importante discutirlo.",
    "¿Alguien más piensa que esto es una locura? 🤯",
    "Me encanta cómo se está desarrollando esta conversación. 🙌",
    "Nunca pensé que diría esto, pero estoy 100% de acuerdo contigo.",
    "Este es el mejor comentario que he leído hoy. 😂",
    "Sigo sin entender por qué la gente sigue hablando de esto...",
    "¿Qué opinan sobre las últimas noticias? Estoy confundido. 🤔",
    "Esto me recuerda a lo que pasó el año pasado. ¿Alguien más lo recuerda?",
    "El arte de argumentar es una habilidad muy subestimada. 💬",
    "¡Esto es tan cierto! No puedo dejar de pensarlo. 🥲",
    "La verdad es que me encanta cómo todos comparten sus opiniones aquí.",
    "No tengo palabras para describir cómo me siento. 😞",
    "Gracias por compartir esto, realmente lo necesitaba. 🙏",
    "Siempre hay dos lados en una historia. 🤷‍♂️",
    "Las redes sociales deberían ser un lugar para el respeto y la amabilidad. 💖",
    "¿Por qué la gente se siente tan cómoda atacando a otros en línea? 😡",
    "Las mejores conversaciones surgen de las diferencias de opinión. 💭",
    "No estoy de acuerdo, pero respeto tu opinión. 😊",
    "Esto es tan relevante en estos días. Todos deberían leerlo.",
    "Las pequeñas cosas pueden marcar una gran diferencia. 🌍",
    "Estoy ansioso por ver cómo se desarrollan las cosas. 📅",
    "¿Alguien más aquí se siente abrumado por toda esta información?",
    "Definitivamente estoy guardando esto para más tarde. 📌",
    "Esto es un gran recordatorio de lo que realmente importa. 💫",
    "La verdad es que todos necesitamos escuchar más y hablar menos. 🤫",
    "¿Alguien tiene recomendaciones de libros sobre este tema? 📚",
    "Lo que dices es tan acertado. La mayoría pasa por alto este detalle.",
    "No hay nada mejor que un buen debate. ¡Sigue así! 🔥",
    "A veces, un cambio de perspectiva es todo lo que necesitamos. 🔄",
    "¡Hablemos de esto en más detalle! Me interesa mucho.",
    "Me encanta ver cómo esta comunidad se une para discutir. 💪",
    "Esto es exactamente lo que estaba buscando. ¡Gracias! 🙌",
    "A veces, lo más pequeño puede tener el mayor impacto. ✨",
    "Es genial ver diferentes puntos de vista sobre un tema tan importante.",
    "Esto me ha hecho reflexionar. Gracias por compartir tu perspectiva. 🧐",
]
